<?xml version="1.0" encoding="{$charset}"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!-- Generated by phpDocumentor on {$date}  -->
        <!-- adapted by Bruno Marques Nogueira -->
        
        <title>{$title}</title>
        <meta http-equiv='Content-Type' content='text/html; charset={$charset}' />
    </head>
    <frameset rows='110,*' framespacing="0" frameborder="0" border="0">
        <frame src='packages.html' name='left_top' scrolling="no" />
        <frameset cols='250,*' framespacing="0" frameborder="0" border="0">
            <frame src='{$start}' name='left_bottom' />
            <frame src='{$blank}.html' name='right' />
        </frameset>
        <noframes>
            <h2>Atenção!!!</h2>
            <p>Seu browser (navegador web) não aceita FRAMESET. Atualize ou utilize outro browser...</p>
        </noframes>
    </frameset>
</html>
