<?php /* Smarty version 2.6.0, created on 2015-03-23 23:42:26
         compiled from index.tpl */ ?>
<?php echo '<?xml'; ?>
 version="1.0" encoding="<?php echo $this->_tpl_vars['charset']; ?>
"<?php echo '?>'; ?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <!-- Generated by phpDocumentor on <?php echo $this->_tpl_vars['date']; ?>
  -->
        <!-- adapted by Bruno Marques Nogueira -->
        
        <title><?php echo $this->_tpl_vars['title']; ?>
</title>
        <meta http-equiv='Content-Type' content='text/html; charset=<?php echo $this->_tpl_vars['charset']; ?>
' />
    </head>
    <frameset rows='110,*' framespacing="0" frameborder="0" border="0">
        <frame src='packages.html' name='left_top' scrolling="no" />
        <frameset cols='250,*' framespacing="0" frameborder="0" border="0">
            <frame src='<?php echo $this->_tpl_vars['start']; ?>
' name='left_bottom' />
            <frame src='<?php echo $this->_tpl_vars['blank']; ?>
.html' name='right' />
        </frameset>
        <noframes>
            <h2>Atenção!!!</h2>
            <p>Seu browser (navegador web) não aceita FRAMESET. Atualize ou utilize outro browser...</p>
        </noframes>
    </frameset>
</html>